# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/collective/zpretty
    rev: 3.1.1
    hooks:
    -   id: zpretty
        exclude: '/.cache'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy

-   repo: https://github.com/KAUTH/git-lfs-hooks
    rev: v3.3.0
    hooks:
    -   id: pre-push

-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.51"
    hooks:
    -   id: check-manifest
        stages: [manual, pre-push]

-   repo: https://github.com/regebro/pyroma
    rev: "5.0.1"
    hooks:
    -   id: pyroma
        stages: [manual, pre-push]

-   repo: https://github.com/mgedmin/check-python-versions
    rev: "0.24.0"
    hooks:
    -   id: check-python-versions
        args: ['--only', 'setup.py,pyproject.toml']
        additional_dependencies: ['setuptools']

-   repo: https://github.com/collective/i18ndude
    rev: "6.3.0"
    hooks:
    -   id: i18ndude
        exclude: '/search\.pt$'

-   repo: local
    hooks:
      - id: todo-check
        name: Check for TODOs
        entry: bash -c 'if grep -n "TODO\|FIXME" "$@"; then echo "⚠️  Found TODOs above - remember to address them!"; fi; exit 0'
        language: system
        types: [text]
        verbose: true # Always show output
        pass_filenames: true
        exclude: ^\.pre-commit-config.yaml
